# Generated by Django 5.2.7 on 2026-06-24 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300, verbose_name='عنوان تگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('title', models.CharField(default='معلم', max_length=100, verbose_name='سمت')),
                ('avatar', models.ImageField(upload_to='instructors/', verbose_name='تصویر مدرس')),
                ('bio', models.TextField(verbose_name='بیوگرافی')),
                ('phone', models.CharField(max_length=20, verbose_name='موبایل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('site_address', models.CharField(max_length=300, verbose_name='آدرس سایت')),
                ('skype_address', models.CharField(max_length=300, verbose_name='آدرس skype')),
                ('pintrest', models.URLField(blank=True, null=True, verbose_name='پینترست')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='توییتر')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فیسبوک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'مدرسان',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان دسته بندی')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف/حذف نشده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentcategories', to='courses_modules.coursecategory')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان دوره')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('duration_days', models.PositiveIntegerField(verbose_name='مدت دوره')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('short_description', models.CharField(db_index=True, max_length=400, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(null=True, verbose_name='توضیحات تکمیلی محصول')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('image', models.ImageField(default='courses/default.jpg', upload_to='courses/', verbose_name='تصویر')),
                ('url_title', models.CharField(blank=True, db_index=True, default='', max_length=300, null=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('overview', models.TextField(verbose_name='بررسی اجمالی')),
                ('section', models.TextField(verbose_name='برنامه تحصیلی')),
                ('lecture_count', models.PositiveIntegerField(verbose_name='کل سخترانی ها')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name=' تعداد دانشجوبان')),
                ('has_certificate', models.BooleanField(default=0, verbose_name='دارای گواهینامه')),
                ('suggested_courses', models.ManyToManyField(blank=True, to='courses_modules.course', verbose_name='دوره های پیشنهادی')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses_modules.coursecategory', verbose_name='دسته بندی محصول')),
                ('course_tag', models.ManyToManyField(to='courses_modules.coursetag', verbose_name='تگ محصول')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses_modules.instructor', verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
            },
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses_modules.course', verbose_name='دوره')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر دوره',
                'verbose_name_plural': 'نظرات دوره',
            },
        ),
    ]
