# Generated by Django 5.2.7 on 2026-06-25 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان معرفی صفحه اصلی')),
                ('text', models.TextField(verbose_name='متن معرفی')),
                ('description', models.TextField(verbose_name='متن معرفی2')),
                ('feature_1', models.CharField(max_length=200, verbose_name='ویژگی اول')),
                ('feature_2', models.CharField(max_length=200, verbose_name='ویژگی دوم')),
                ('feature_3', models.CharField(max_length=200, verbose_name='ویژگی سوم')),
                ('main_img', models.ImageField(upload_to='site/about/', verbose_name='تصویر معرفی اصلی')),
                ('img', models.ImageField(upload_to='site/about/', verbose_name='تصویر معرفی 2')),
            ],
            options={
                'verbose_name': 'تنظیمات سکشن معرفی ',
                'verbose_name_plural': ' تنظیمات سکشن معرفی',
            },
        ),
        migrations.CreateModel(
            name='AbouUsFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان صفحه درباره ما')),
                ('text', models.TextField(verbose_name='توضیحات صفحه درباره ما')),
                ('feature_1_title', models.CharField(max_length=200, verbose_name='عنوان ویژگی اول')),
                ('feature_1_text', models.TextField(verbose_name='متن ویژگی اول')),
                ('feature_2_title', models.CharField(max_length=200, verbose_name='عنوان ویژگی دوم')),
                ('feature_2_text', models.TextField(verbose_name='متن ویژگی دوم')),
                ('feature_3_title', models.CharField(max_length=200, verbose_name='عنوان ویژگی سوم')),
                ('feature_3_text', models.TextField(verbose_name='متن ویژگی سوم')),
                ('feature_4_title', models.CharField(max_length=200, verbose_name='عنوان ویژگی چهارم')),
                ('feature_4_text', models.TextField(verbose_name='متن ویژگی چهارم')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان بنر')),
                ('description', models.TextField(verbose_name='توضیحات بنر')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='تصویر بنر')),
                ('button_text', models.CharField(max_length=100, verbose_name='متن دکمه')),
                ('button_link', models.CharField(max_length=300, verbose_name='لینک دکمه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرهای سایت',
            },
        ),
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('become_instructor_title', models.CharField(max_length=300, verbose_name='عنوان بخش مربی')),
                ('become_instructor_text', models.TextField(verbose_name='متن بخش مربی')),
                ('student_title', models.CharField(max_length=300, verbose_name='عنوان بخش دانشجو')),
                ('student_text', models.TextField(verbose_name='متن بخش دانشجو')),
            ],
            options={
                'verbose_name': 'تنظیمات دعوت به همکاری ',
                'verbose_name_plural': ' تنظیمات دعوت به همکاری',
            },
        ),
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='لوگوی شرکت')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک شرکت')),
            ],
            options={
                'verbose_name': 'لوگوی همکار',
                'verbose_name_plural': 'لوگوهای همکاران',
            },
        ),
        migrations.CreateModel(
            name='FooterLinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=200, verbose_name='دامنه سایت')),
                ('address', models.TextField(max_length=200, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='ایمیل')),
                ('copy_right', models.CharField(blank=True, max_length=300, null=True, verbose_name='متن کپی رایت')),
                ('about_us_text', models.TextField(max_length=200, verbose_name='متن درباره ما سایت')),
                ('site_logo', models.ImageField(upload_to='site_setting/', verbose_name='لوگو سایت')),
                ('video_background', models.FileField(blank=True, null=True, upload_to='site/videos/', verbose_name='ویدیوی پس زمینه')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='لینک فیسبوک')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='لینک توییتر')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='لینک یوتیوب')),
                ('pinterest_link', models.URLField(blank=True, null=True, verbose_name='لینک پینترست')),
                ('tumblr_link', models.URLField(blank=True, null=True, verbose_name='لینک تامبلر')),
                ('rss_link', models.URLField(blank=True, null=True, verbose_name='لینک RSS')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینک لینکدین')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.CharField(max_length=200, verbose_name='لینک')),
                ('footer_link_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='site_setting.footerlinkbox', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': ' لینک های فوتر',
            },
        ),
    ]
