# Generated by Django 5.2.7 on 2026-06-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouusfeature',
            options={'verbose_name': 'تنظیمات ویژگی صفحه درباره ما ', 'verbose_name_plural': 'تنظیمات ویژگی صفحه درباره ما'},
        ),
        migrations.AddField(
            model_name='banner',
            name='background',
            field=models.ImageField(default='', upload_to='sliders/', verbose_name='بکگراند بنر'),
            preserve_default=False,
        ),
    ]
