# Generated by Django 5.2.7 on 2026-06-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0002_alter_abouusfeature_options_banner_background'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text',
        ),
    ]
