# Generated by Django 5.2.7 on 2026-06-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0003_alter_sitesetting_options_remove_banner_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='img',
        ),
    ]
