# Generated by Django 5.2.7 on 2026-06-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0004_remove_about_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlinkbox',
            options={'verbose_name': 'عنوان لینک فوتر', 'verbose_name_plural': 'عنوان لینک های فوتر'},
        ),
    ]
