# Generated by Django 5.2.7 on 2026-06-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300, verbose_name='عنوان پیام')),
                ('Email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('Fullname', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('Message', models.TextField(verbose_name='متن پیام مخاطب')),
                ('is_read_admin', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پیام')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
    ]
